dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - psql -c "create user test_user with password 'password';" -U postgres
  - psql -c 'create database moodster_test;' -U postgres
  - psql -c "alter role test_user superuser;" -U postgres
  - psql -c 'alter database moodster_test owner to test_user;' -U postgres
env:
  - DATABASE_URL=postgresql://test_user:password@localhost/moodster_test
script:
  - python -m unittest discover app/tests/
