"""Renamed team_members to membership for clarity in places.

Revision ID: 077025932055
Revises: 82a9891bbadc
Create Date: 2019-07-26 22:34:40.541748

"""
from alembic import op, context


# revision identifiers, used by Alembic.
revision = '077025932055'
down_revision = '82a9891bbadc'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('team_member', 'membership')
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('membership', 'team_member')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
